import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MANUTENCAO = false; // ⬅️ mudar para false quando terminar a migração

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {MANUTENCAO ? (
          <main className="min-h-screen bg-zinc-950 text-white flex items-center justify-center text-center p-4">
            <div>
              <h1 className="text-2xl font-black mb-2">⚽ Voltamos já!</h1>
              <p className="text-zinc-400">
                Manutenção rápida no bolão. Tenta de novo em alguns minutos 😉
              </p>
            </div>
          </main>
        ) : (
          children
        )}
      </body>
    </html>
  );
}